# Generated by Django 5.1.1 on 2024-09-20 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id_asistencia', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('empleado_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Nomina',
            fields=[
                ('id_nomina', models.AutoField(primary_key=True, serialize=False)),
                ('empleado_id', models.IntegerField()),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_pago', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id_permiso', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pqrs',
            fields=[
                ('idPqrs', models.AutoField(primary_key=True, serialize=False)),
                ('asunto', models.CharField(max_length=500)),
                ('fechaRadicado', models.DateField()),
                ('contenidoPqrs', models.CharField(max_length=500)),
                ('fkCliente', models.IntegerField()),
            ],
        ),
    ]
